feat: add download study button
ImagingDataCommons/idc-slim pull request #109
Opened 2024-10-17 21:28 UTC by pedrokohler

Adding button to download study/series:

![image](https://github.com/user-attachments/assets/1df5dbeb-731b-40cf-9a8a-35e17258ea2e)

2024-10-17 21:31 UTC, pedrokohler commented
@fedorov please take a look

2024-10-18 13:03 UTC, igoroctaviano requested changes

2024-10-18 13:03 UTC, igoroctaviano commented on src/components/DownloadStudySeriesDialog.tsx
> +const getStudyAndSeriesInfo = (): {
Please add js docs/types for every function

2024-10-18 13:03 UTC, igoroctaviano commented on src/components/DownloadStudySeriesDialog.tsx
> +  const defaultConfig = {
Can we expose this to slim's configuration? so then we can customize these values without having to build the viewer again

2024-10-18 16:28 UTC, fedorov commented
Looks good to me, thank you!

@pedrokohler I assume, similar to OHIF, it is not trivial to hyperlink idc-index in this popup, right?

2024-10-18 16:34 UTC, pedrokohler commented
> Looks good to me, thank you!
> 
> @pedrokohler I assume, similar to OHIF, it is not trivial to hyperlink idc-index in this popup, right?

It's the same thing: doable in an hour or so, because the content of the dialog is variable, so we must parse the config strings to display the hyperlink.

2024-10-18 22:07 UTC, fedorov commented
Let's go ahead as is then! We can address both at a later time to add hyperlink processing.

2024-10-22 15:00 UTC, igoroctaviano approved these changes
LGTM

2024-10-22 15:00 UTC, merged